package g8;

import com.google.android.gms.common.api.Status;
import d.m0;
import f8.o;
import f8.u;
import f8.v;
import f8.x;
import f8.y;
import j8.s;
import j8.w;
import java.util.concurrent.TimeUnit;

public final class u1<R extends u> extends o<R> {

    /* renamed from: a  reason: collision with root package name */
    public final Status f8278a;

    public u1(Status status) {
        s.m(status, "Status must not be null");
        s.b(!status.r1(), "Status must not be success");
        this.f8278a = status;
    }

    public final void c(@m0 o.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @m0
    public final R d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @m0
    public final R e(long j10, @m0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final boolean g() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void h(@m0 v<? super R> vVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void i(@m0 v<? super R> vVar, long j10, @m0 TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @w
    @m0
    public final <S extends u> y<S> j(@m0 x<? super R, ? extends S> xVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @m0
    public final Status k() {
        return this.f8278a;
    }
}
